-- Zabisa DT MySQL security-boundary template.
--
-- Do not execute this file directly. It is rendered by
-- scripts/provision-zabisa-mysql-vault.sh for every bounded client source in
-- MYSQL_ACCOUNT_NETWORKS. Password and host placeholders must never be
-- committed with real values. Docker Compose intentionally mounts only
-- 00-databases.sql so this operator template cannot run during local startup.

CREATE DATABASE IF NOT EXISTS identity_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS content_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS student_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tahfidz_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS academic_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS donation_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS notification_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'zabisa_identity_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${IDENTITY_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_identity_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${IDENTITY_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_identity_app'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE ON identity_db.* TO 'zabisa_identity_app'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_identity_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${IDENTITY_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_identity_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${IDENTITY_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_identity_migrator'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON identity_db.* TO 'zabisa_identity_migrator'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_content_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${CONTENT_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_content_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${CONTENT_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_content_app'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE ON content_db.* TO 'zabisa_content_app'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_content_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${CONTENT_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_content_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${CONTENT_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_content_migrator'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON content_db.* TO 'zabisa_content_migrator'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_student_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${STUDENT_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_student_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${STUDENT_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_student_app'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE ON student_db.* TO 'zabisa_student_app'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_student_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${STUDENT_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_student_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${STUDENT_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_student_migrator'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON student_db.* TO 'zabisa_student_migrator'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_tahfidz_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${TAHFIDZ_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_tahfidz_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${TAHFIDZ_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_tahfidz_app'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE ON tahfidz_db.* TO 'zabisa_tahfidz_app'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_tahfidz_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${TAHFIDZ_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_tahfidz_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${TAHFIDZ_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_tahfidz_migrator'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON tahfidz_db.* TO 'zabisa_tahfidz_migrator'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_academic_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${ACADEMIC_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_academic_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${ACADEMIC_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_academic_app'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE ON academic_db.* TO 'zabisa_academic_app'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_academic_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${ACADEMIC_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_academic_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${ACADEMIC_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_academic_migrator'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON academic_db.* TO 'zabisa_academic_migrator'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_donation_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${DONATION_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_donation_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${DONATION_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_donation_app'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE ON donation_db.* TO 'zabisa_donation_app'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_donation_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${DONATION_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_donation_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${DONATION_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_donation_migrator'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON donation_db.* TO 'zabisa_donation_migrator'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_notification_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${NOTIFICATION_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_notification_app'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${NOTIFICATION_APP_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_notification_app'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE ON notification_db.* TO 'zabisa_notification_app'@'${MYSQL_ACCOUNT_HOST}';

CREATE USER IF NOT EXISTS 'zabisa_notification_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${NOTIFICATION_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
ALTER USER 'zabisa_notification_migrator'@'${MYSQL_ACCOUNT_HOST}' IDENTIFIED BY '${NOTIFICATION_MIGRATOR_PASSWORD}' REQUIRE SSL PASSWORD EXPIRE NEVER;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'zabisa_notification_migrator'@'${MYSQL_ACCOUNT_HOST}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES ON notification_db.* TO 'zabisa_notification_migrator'@'${MYSQL_ACCOUNT_HOST}';
