CREATE TABLE IF NOT EXISTS payment_accounts (
  id CHAR(36) PRIMARY KEY,
  method_code VARCHAR(64) NOT NULL UNIQUE,
  display_name VARCHAR(160) NOT NULL,
  bank_name VARCHAR(120) NULL,
  account_number VARCHAR(120) NULL,
  account_holder VARCHAR(180) NULL,
  instructions TEXT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
