#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
TARGET="$ROOT/apps/mobile/src/config/runtime.ts"
ENV_NAME=${ZABISA_ENV:-local}
case "$ENV_NAME" in
  local) DEFAULT_URL='http://127.0.0.1:8088' ;;
  dt) DEFAULT_URL='' ;;
  staging) DEFAULT_URL='' ;;
  production) DEFAULT_URL='' ;;
  *) echo "Unsupported ZABISA_ENV=$ENV_NAME (local|dt|staging|production)" >&2; exit 2 ;;
esac
API_URL=${ZABISA_API_URL:-$DEFAULT_URL}
if [[ -z "$API_URL" ]]; then
  echo "ZABISA_API_URL is required for environment '$ENV_NAME'." >&2
  exit 2
fi
if [[ "$ENV_NAME" != local && "$API_URL" != https://* ]]; then
  echo "Non-local mobile API must use HTTPS: $API_URL" >&2
  exit 2
fi
python3 - "$TARGET" "$ENV_NAME" "$API_URL" <<'PY'
from pathlib import Path
import sys
p=Path(sys.argv[1]); env=sys.argv[2]; url=sys.argv[3].rstrip('/')
p.parent.mkdir(parents=True,exist_ok=True)
p.write_text(f"""/** Generated by scripts/mobile-env.sh. Do not place secrets here. */
export const runtimeConfig = {{
  environment: {env!r},
  apiUrl: {url!r},
}} as const;
""")
PY
echo "Mobile environment: $ENV_NAME"
echo "Mobile API URL: $API_URL"
